# Changes from the Other 
# New Test Changes
Run  sh  ./opt/apache-jmeter-5.1.1/bin/jmeter.sh \
    -n -X \
    -Jclient.rmi.localport=7000 \
    -R jmeter-lg1,jmeter-lg2 \
    -t /GitHubJmeterTest.jmx.jmx \
    -l /result.jtl \
    -j /jmeter.log

